---
title: "Teaching"
output:
  html_document:
    toc: true
    toc_float: true
---

I am a firm believer in active and enjoyable learning environments.  I also strive to lower the barriers that students from underrepresented groups face in education.  If you want to know more about me, take a look at my [teaching statement](./docs/TeachingStatement.pdf) and my [diversity statement](./docs/DiversityStatement.pdf).  

<link rel="stylesheet" href="styles.css" type="text/css">

## Solo Instructor

*   **Math 266/267: Elementary Differential Equations**
    Iowa State University, Ames IA, Summer 2018

*   **Math 266/267: Elementary Differential Equations**
    Iowa State University, Ames IA, Summer 2017
    
## Recitation Instructor

*   **Math 265: Multivariate Calculus**
    Iowa State University, Ames IA, Fall 2020
    
*   **Math 140: College Algebra**
    Iowa State University, Ames IA, Fall 2017
    
*   **Math 266/267: Elementary Differential Equations**
    Iowa State University, Ames, IA, Spring 2017

*   **Math 165: Calculus I**
    Iowa State University, Ames, IA, Fall 2016
    
## Grader

*   **Math 566: Discrete Optimization**
    Iowa State University, Ames, IA, Fall 2018

*   **Math 201: Introduction to Proofs**
    Iowa State University, Ames, IA, Spring 2018

*   **Math 439: Fractals and Chaos**
    Iowa State University, Ames, IA, Spring 2018
